services:
  db:
    image: postgres:16
    container_name: erp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp123
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"
    volumes:
      - erp_pgdata:/var/lib/postgresql/data

volumes:
  erp_pgdata: